dataset:
  name: CIFAR10
  data_root: ./data/processed/CIFAR10
  num_classes: 10
  image_size: 32
  channels: 3
  normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2470, 0.2435, 0.2616]
  download: true
  split:
    train_ratio: 0.9
    test_ratio: 0.1
